from __future__ import annotations


AUTHOR_SIDE_ROUTE_IDS = (
    "direction_screening",
    "question_refinement",
    "argument_building",
    "fit_alignment",
    "outline",
    "drafting",
    "critique",
    "revision",
    "frozen",
    "artifact_bundle",
    "final_package",
    "hosted_contract_bundle",
)

SUPPORTED_DOMAIN_ENTRY_COMMANDS = [
    "validate-workspace",
    "summarize-workspace",
    "grant-intake-audit",
    "grant-evidence-grounding",
    "grant-quality-scorecard",
    "grant-quality-diff",
    "grant-quality-closure-dossier",
    "discover-funding-opportunities",
    "refresh-funding-opportunities-cache",
    "select-project-profile",
    "initialize-intake-workspace",
    "next-step",
    "critique-summary",
    "stage-route-report",
    "execute-direction-screening-pass",
    "execute-question-refinement-pass",
    "execute-argument-building-pass",
    "execute-fit-alignment-pass",
    "execute-outline-pass",
    "execute-drafting-pass",
    "build-artifact-bundle",
    "execute-critique-pass",
    "execute-critique-revision-loop",
    "execute-authoring-mainline-loop",
    "execute-grant-autonomy-controller",
    "execute-revision-pass",
    "execute-freeze-pass",
    "build-final-package",
    "build-hosted-contract-bundle",
    "build-submission-ready-package",
]

DOMAIN_ENTRY_COMMAND_CONTRACTS = [
    {"command": "validate-workspace", "required_fields": ["input_path"], "optional_fields": []},
    {"command": "summarize-workspace", "required_fields": ["input_path"], "optional_fields": []},
    {"command": "grant-intake-audit", "required_fields": ["input_path"], "optional_fields": []},
    {"command": "grant-evidence-grounding", "required_fields": ["input_path"], "optional_fields": []},
    {"command": "grant-quality-scorecard", "required_fields": ["input_path"], "optional_fields": []},
    {"command": "grant-quality-closure-dossier", "required_fields": ["input_path"], "optional_fields": []},
    {
        "command": "grant-quality-diff",
        "required_fields": ["input_path", "previous_input_path"],
        "optional_fields": [],
    },
    {"command": "discover-funding-opportunities", "required_fields": ["input_path"], "optional_fields": []},
    {
        "command": "refresh-funding-opportunities-cache",
        "required_fields": ["input_path"],
        "optional_fields": ["output_path"],
    },
    {"command": "select-project-profile", "required_fields": ["input_path"], "optional_fields": []},
    {
        "command": "initialize-intake-workspace",
        "required_fields": ["input_path"],
        "optional_fields": ["output_path", "workspace_root", "initialize_git"],
    },
    {"command": "next-step", "required_fields": ["input_path"], "optional_fields": []},
    {"command": "critique-summary", "required_fields": ["input_path"], "optional_fields": []},
    {"command": "stage-route-report", "required_fields": ["input_path"], "optional_fields": []},
    {"command": "execute-direction-screening-pass", "required_fields": ["input_path", "output_path"], "optional_fields": []},
    {"command": "execute-question-refinement-pass", "required_fields": ["input_path", "output_path"], "optional_fields": []},
    {"command": "execute-argument-building-pass", "required_fields": ["input_path", "output_path"], "optional_fields": []},
    {"command": "execute-fit-alignment-pass", "required_fields": ["input_path", "output_path"], "optional_fields": []},
    {"command": "execute-outline-pass", "required_fields": ["input_path", "output_path"], "optional_fields": []},
    {"command": "execute-drafting-pass", "required_fields": ["input_path", "output_path"], "optional_fields": []},
    {"command": "build-artifact-bundle", "required_fields": ["input_path", "output_path"], "optional_fields": []},
    {
        "command": "execute-critique-pass",
        "required_fields": ["input_path", "output_path"],
        "optional_fields": ["executor_kind"],
    },
    {
        "command": "execute-critique-revision-loop",
        "required_fields": ["input_path", "output_dir"],
        "optional_fields": ["max_rounds", "executor_kind"],
    },
    {
        "command": "execute-authoring-mainline-loop",
        "required_fields": ["input_path", "output_dir"],
        "optional_fields": ["max_cycles", "executor_kind"],
    },
    {
        "command": "execute-grant-autonomy-controller",
        "required_fields": ["input_path", "output_dir"],
        "optional_fields": ["executor_kind"],
    },
    {"command": "execute-revision-pass", "required_fields": ["input_path", "output_path"], "optional_fields": []},
    {"command": "execute-freeze-pass", "required_fields": ["input_path", "output_path"], "optional_fields": []},
    {
        "command": "build-final-package",
        "required_fields": ["input_path", "artifact_bundle_path", "output_path"],
        "optional_fields": [],
    },
    {
        "command": "build-hosted-contract-bundle",
        "required_fields": ["final_package_path", "output_path"],
        "optional_fields": [],
    },
    {
        "command": "build-submission-ready-package",
        "required_fields": ["input_path", "output_dir"],
        "optional_fields": [],
    },
]

CANONICAL_EXPORT_SURFACES = [
    "execute-direction-screening-pass",
    "execute-question-refinement-pass",
    "execute-argument-building-pass",
    "execute-fit-alignment-pass",
    "execute-outline-pass",
    "execute-drafting-pass",
    "execute-critique-pass",
    "execute-revision-pass",
    "execute-freeze-pass",
    "build-artifact-bundle",
    "build-final-package",
    "build-hosted-contract-bundle",
    "build-submission-ready-package",
]
